### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by map1223** [YimingMa/FusionCount#1]
Could you please send me all the codes of your paper？Thanks! my E-mail:2834583572@qq.com

**Comment by Yiming-M** [comment]
Hi @map1223,

Unfortunately I am unable and not supposed to provide the code to any private source.  Could you please let me know what problems you have encountered?

Many thanks,
Yiming

**Comment by Yiming-M** [comment]
Hi @map1223,

Since there has been any response for more than one month, this issue is going to be closed. Please feel free to open it again if you encounter any other problems.

Best wishes,
Yiming
